# Generated by Django 3.1.6 on 2021-04-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentalcheck', '0002_auto_20210413_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontext',
            name='idNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questiontext',
            name='questionText',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiontext',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiontext',
            name='userAnswered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
