# Generated by Django 3.1.6 on 2021-05-05 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentalcheck', '0004_auto_20210505_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontext',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='questiontext',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
